export const ActionTypes = {
  SET_VIEW: "VIEW CHANGED",
  SET_NOTIFICATION: "NOTIFICATION ADDED",
  SET_CONTENT_IMAGE: "CONTENT IMAGE ADDED",
  SET_STYLE_IMAGE: "STYLE IMAGE ADDED",
  SET_OUTPUT_IMAGE: "OUTPUT IMAGE ADDED",
  SET_NST_PROCESSING: "NST PROCESSING",
  SET_IMAGE_UPLOAD_TEXT: "IMAGE UPLOAD SECTION TEXT CHANGED",
};
